name: aniwhiz
description: "No Anime No Life"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # Firebase
  firebase_core: ^3.6.0
  
  # Image
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1

  # Icon
  flutter_lucide: ^1.7.0
  fluentui_system_icons: ^1.1.258
  
  # Animation
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/